import { Pokemon, Move, ElementType } from './types';

export const TYPE_CHART: Record<ElementType, Record<ElementType, number>> = {
  normal: { normal: 1, fire: 1, water: 1, grass: 1, electric: 1 },
  fire: { normal: 1, fire: 0.5, water: 0.5, grass: 2, electric: 1 },
  water: { normal: 1, fire: 2, water: 0.5, grass: 0.5, electric: 1 },
  grass: { normal: 1, fire: 0.5, water: 2, grass: 0.5, electric: 1 },
  electric: { normal: 1, fire: 1, water: 2, grass: 0.5, electric: 0.5 },
};

export const MOVES: Record<string, Move> = {
  // Normal Moves
  scratch: { id: 'scratch', name: 'Scratch', type: 'normal', power: 40, accuracy: 100, description: 'Scratches the target.' },
  tackle: { id: 'tackle', name: 'Tackle', type: 'normal', power: 40, accuracy: 100, description: 'Charges the foe.' },
  quickattack: { id: 'quickattack', name: 'Quick Attack', type: 'normal', power: 40, accuracy: 100, description: 'Moves fast to strike first.' },
  bite: { id: 'bite', name: 'Bite', type: 'normal', power: 60, accuracy: 100, description: 'Bites with vicious fangs.' },
  bodyslam: { id: 'bodyslam', name: 'Body Slam', type: 'normal', power: 85, accuracy: 100, description: 'Drops full body weight on the foe.' },
  swift: { id: 'swift', name: 'Swift', type: 'normal', power: 60, accuracy: 100, description: 'Sprays star-shaped rays.' },
  hyperbeam: { id: 'hyperbeam', name: 'Hyper Beam', type: 'normal', power: 150, accuracy: 90, description: 'A powerful beam.' },
  
  // Fire Moves
  ember: { id: 'ember', name: 'Ember', type: 'fire', power: 40, accuracy: 100, description: 'A weak fire attack.' },
  flamethrower: { id: 'flamethrower', name: 'Flamethrower', type: 'fire', power: 90, accuracy: 100, description: 'A powerful fire attack.' },
  fireblast: { id: 'fireblast', name: 'Fire Blast', type: 'fire', power: 110, accuracy: 85, description: 'A blast of fire.' },
  
  // Water Moves
  watergun: { id: 'watergun', name: 'Water Gun', type: 'water', power: 40, accuracy: 100, description: 'Squirts water to attack.' },
  hydropump: { id: 'hydropump', name: 'Hydro Pump', type: 'water', power: 110, accuracy: 80, description: 'A huge volume of water.' },
  bubblebeam: { id: 'bubblebeam', name: 'Bubble Beam', type: 'water', power: 65, accuracy: 100, description: 'Forcefully sprays bubbles.' },
  surf: { id: 'surf', name: 'Surf', type: 'water', power: 90, accuracy: 100, description: 'Creates a giant wave.' },
  
  // Grass Moves
  vinewhip: { id: 'vinewhip', name: 'Vine Whip', type: 'grass', power: 45, accuracy: 100, description: 'Strikes with slender whips.' },
  solarbeam: { id: 'solarbeam', name: 'Solar Beam', type: 'grass', power: 120, accuracy: 100, description: 'Absorbs light to attack.' },
  razorleaf: { id: 'razorleaf', name: 'Razor Leaf', type: 'grass', power: 55, accuracy: 95, description: 'Slashes with sharp leaves.' },
  energyball: { id: 'energyball', name: 'Energy Ball', type: 'grass', power: 90, accuracy: 100, description: 'Draws power from nature.' },
  
  // Electric Moves
  thundershock: { id: 'thundershock', name: 'Thunder Shock', type: 'electric', power: 40, accuracy: 100, description: 'A jolt of electricity.' },
  thunderbolt: { id: 'thunderbolt', name: 'Thunderbolt', type: 'electric', power: 90, accuracy: 100, description: 'A strong electric blast.' },
  thunder: { id: 'thunder', name: 'Thunder', type: 'electric', power: 110, accuracy: 70, description: 'A wicked thunderbolt.' },
};

export const POKEMON_ROSTER: Pokemon[] = [
  {
    id: 4,
    name: 'Charmander',
    type: 'fire',
    maxHp: 120,
    attack: 52,
    defense: 43,
    speed: 65,
    moves: [MOVES.scratch, MOVES.ember, MOVES.flamethrower, MOVES.quickattack],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',
  },
  {
    id: 7,
    name: 'Squirtle',
    type: 'water',
    maxHp: 125,
    attack: 48,
    defense: 65,
    speed: 43,
    moves: [MOVES.tackle, MOVES.watergun, MOVES.hydropump, MOVES.bubblebeam],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',
  },
  {
    id: 1,
    name: 'Bulbasaur',
    type: 'grass',
    maxHp: 125,
    attack: 49,
    defense: 49,
    speed: 45,
    moves: [MOVES.tackle, MOVES.vinewhip, MOVES.solarbeam, MOVES.razorleaf],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png',
  },
  {
    id: 25,
    name: 'Pikachu',
    type: 'electric',
    maxHp: 100,
    attack: 55,
    defense: 40,
    speed: 90,
    moves: [MOVES.quickattack, MOVES.thundershock, MOVES.thunderbolt, MOVES.tackle],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
  },
  {
    id: 133,
    name: 'Eevee',
    type: 'normal',
    maxHp: 110,
    attack: 55,
    defense: 50,
    speed: 55,
    moves: [MOVES.tackle, MOVES.quickattack, MOVES.bite, MOVES.swift],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/133.png',
  },
  {
    id: 143,
    name: 'Snorlax',
    type: 'normal',
    maxHp: 160,
    attack: 80,
    defense: 65,
    speed: 30,
    moves: [MOVES.bodyslam, MOVES.bite, MOVES.scratch, MOVES.tackle],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/143.png',
  },
  {
    id: 58,
    name: 'Growlithe',
    type: 'fire',
    maxHp: 110,
    attack: 70,
    defense: 45,
    speed: 60,
    moves: [MOVES.ember, MOVES.bite, MOVES.flamethrower, MOVES.quickattack],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/58.png',
  },
  {
    id: 43,
    name: 'Oddish',
    type: 'grass',
    maxHp: 105,
    attack: 50,
    defense: 55,
    speed: 30,
    moves: [MOVES.razorleaf, MOVES.vinewhip, MOVES.tackle, MOVES.solarbeam],
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/43.png',
  },
  {
    id: 160,
    name: 'Abyssal Guardian',
    type: 'water',
    maxHp: 140,
    attack: 85,
    defense: 80,
    speed: 78,
    moves: [MOVES.hydropump, MOVES.bite, MOVES.surf, MOVES.bodyslam],
    // Switched to Gyarados sprites to look like a real monster instead of a diagram
    frontImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    backImage: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/130.png',
  },
];